services:
  lawcontroller-ui:
    build: .
    container_name: lawcontroller-ui
    ports:
      - "3100:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - .:/app
    working_dir: /app
    command: >
      sh -c "npm install &&
             npm run build &&
             npm run start -- -H 0.0.0.0"
